# These are supported funding model platforms
github: [pedroSG94]
patreon: pedroSG94
custom: ['https://www.paypal.com/paypalme/pedroSG94']
 # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
